services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - database_network
    restart: unless-stopped

  app:
    build:
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    env_file: .env
    restart: on-failure
    depends_on:
      - db
      - redis
    networks:
      - database_network
    ports:
      - "8000:8000"
    expose:
      - 8000

  worker:
    build:
      dockerfile: Dockerfile
    command: celery -A app.celery_app:celery_app worker --loglevel=INFO --pool=prefork -Q messages,audio,image,video,tts
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis
    restart: on-failure
    networks:
      - database_network

  beat:
    build:
      dockerfile: Dockerfile
    command: celery -A app.celery_app:celery_app beat --loglevel=INFO
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - redis
    restart: on-failure
    networks:
      - database_network


volumes:
  postgres_data:
  redis_data:
networks:
  database_network:
